name: NestJS API CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  conventions:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    name: Naming convention checks
    strategy:
      matrix:
        node-version: [ 22.x ]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Generate JWT
        run: echo "JWT=$(bash scripts/generate-jwt.sh)" >> "$GITHUB_ENV"
      - run: node --experimental-strip-types --experimental-transform-types --no-warnings=ExperimentalWarnings scripts/check-commit-naming.ts
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
